### PR TITLE
automatically renew auth token

### PR DESCRIPTION
**Pull request by segura2010**
I also use npm package of node-pogo-signature and s2-geometry (s2-geometry implementation in pure JS). Both works well.

### CODE REVIEW

**Comment by WesVleuten** [comment]
This will probably resolve one of the issues mentioned in #220

**Comment by cpainchaud** [comment]
since S2 usage was merged earlier, I think you need to close this PR et make a new one with just yyou auth-ticket renew ?

**Comment by segura2010** [comment]
@cpainchaud yes, you are right :) I will prepare a new PR asap

**Comment by marvi14** [comment]
Did someone manage to renew token from an expired accessToken? the thing is that renewing the token with username and password is possible, but when the users logs in with google, the google AuthCode is expired, and i don't want the user to relog with google again

**Pull request closed without merging**
