### PR TITLE
Merge files from SzymonLisowiec

### PR DESCRIPTION
**Pull request by Bart-0110**
This includes support for GetInventory and better AvatarDetails support.
I tested it for a bit and it seems to work correctly.

### CODE REVIEW

**Comment by Armax** [comment]
Nice work :) I will test it and merge, anyway if you want reach us on discord https://discord.gg/jaDx9rJ channel: node_dev

**Comment by Armax** [comment]
Anyway atm GetInventory function is throwing a `Error: Illegal wire type for field Message.Field .ResponseEnvelop.PokemonData.additional_cp_multiplier: 5 (0 expected)` maybe give it a check

**Comment by Bart-0110** [comment]
I'm sorry I can't test it right now, servers are down (again). I should credit @SzymonLisowiec because he did the hard work. I only merged it :)

**Comment by SzymonLisowiec** [comment]
I'm sorry, I'm still learning how to operate a github. ;p
I modeled on: https://github.com/tejado/pgoapi

**Comment by fr0th** [comment]
Really nice work on this one guys :+1:

**Pull request merged**
