### PR TITLE
Fix error/crash when xdat is undefined

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
example.js:116
                                console.log(status[xdat.Status]);
                                                       ^
TypeError: Cannot read property 'Status' of undefined

### CODE REVIEW

**Comment by LocutusOfBorg** [comment]
it is not happening everytime, but so often in the last few days, probably the server is not answering correctly due to highload, and the example code crashes

**Comment by BlackRosie** [comment]
this seems to be coming back undefined every attempt now anyone else ?

**Comment by LocutusOfBorg** [comment]
it really depends on the server I guess

**Comment by BlackRosie** [comment]
maybe i was put on a shadow ban, but this seems to return undefined and never catches the encountered pokemon.

**Comment by Vlek** [comment]
The Niantic servers aren't going to send you what you want when you expect it every time. Really, your code should be able to handle these error cases. So, in this case, instead of assuming you're going to get xdat.Status, you should first check whether you have it before using it. This is just good practice in general regardless of one's project.

**Pull request closed without merging**
