### PR TITLE
Get rid of NearbyPokemon[0].DistanceMeters.toString()

### PR DESCRIPTION
**Pull request by GcodeS**
NearbyPokemon[0].DistanceMeters.toString() is now returning to null. It breaks the code.

### CODE REVIEW

**Comment by andnp** [comment]
You might also create an issue in the s2-geometry repository to add this functionality to their API.

**Comment by GcodeS** [comment]
@andnp it isn't their fault. Pokemon Go is now returning every distance null, so toString() cannot work properly.

**Comment by RedSparr0w** [comment]
incase it starts working again ive just changed my code to:

``` javascript
console.log(pokemon.name + ' spotted ' + ( hb.cells[i].NearbyPokemon[n].DistanceMeters ?  hb.cells[i].NearbyPokemon[n].DistanceMeters.toString()+' meters away' : 'nearby' ));
```

which would output `Zubat spotted nearby` if `DistanceMeters==null`

**Comment by fr0th** [comment]
+1

**Pull request merged**
