### PR TITLE
add serialize / deserialize

### PR DESCRIPTION
**Pull request by coolaj86**
Addresses #69 and #75. Seems to work. See usage in https://github.com/coolaj86/node-pokemap

### CODE REVIEW

**Comment by coolaj86** [comment]
Hmm... still needs to be added to documentation...

**Comment by coolaj86** [comment]
bump.

Can we merge this please?

**Comment by coolaj86** [comment]
Added documentation. Now ready to merge.

**Comment by coolaj86** [comment]
What's the hold up on getting this merged in?

It's working well and the docs have been updated accordingly.

**Comment by RedSparr0w** [comment]
Nothing seems to have been merged/closed in awhile.

Project may need some more maintainers

**Pull request closed without merging**
