### PR TITLE
Move to ES5

### PR DESCRIPTION
**Pull request by Bart-0110**
This needs to be tested. Because I can't build the project for some reason I can't test it myself.

### CODE REVIEW

**Comment by d-pollard** [comment]
@Armax can we revert it?

**Comment by Armax** [comment]
we decided to use ES5 in order to avoid peoples opening issue for a node version <6, and also for personal preference

**Comment by d-pollard** [comment]
You should make an ES6 Branch instead of scrapping all the ES6 work - I'd happily help you maintain it if you'd like @Armax

**Comment by st0ffern** [comment]
@d-pollard https://github.com/stoffern/pokemon-go-api
its all ES6 ;) async and multithreaded ;)
work in progress tho

**Pull request merged**
