### PR TITLE
added posibility to include device info to simulate real device

### PR DESCRIPTION
**Pull request by segura2010**

### CODE REVIEW

**Comment by SpencerSharkey** [comment]
awesome :dancer:

**Comment by williamokano** [comment]
Not sure how to extract these data.

**Comment by Josebaseba** [comment]
How important is this to don't be detected? Do you notice the difference in your app? 

Can you give us an example of valid data, I don't know how to fill it properly.

**Comment by williamokano** [comment]
Just call Pokeio.SerDeviceInfo({device_id: "SomeId"}); before Pomeio.init.

You can find your id using some app for this, like Android Id (on play
store).

Em seg, 8 de ago de 2016 07:14, Joseba Legarreta notifications@github.com
escreveu:

**Comment by segura2010** [comment]
@Josebaseba  you can find these values with adb

```
"DeviceId": "", // adb.exe shell settings get secure android_id
"AndroidBoardName": "", // adb.exe shell getprop ro.product.board
"AndroidBootloader": "", // adb.exe shell getprop ro.boot.bootloader
"DeviceBrand": "", // adb.exe shell getprop ro.product.brand
"DeviceModel": "", // adb.exe shell getprop ro.product.model
"DeviceModelIdentifier": "", // adb.exe shell getprop ro.product.name
"DeviceModelBoot": "qcom",
"HardwareManufacturer": "", // adb.exe shell getprop ro.product.manufacturer
"HardwareModel": "", // adb.exe shell getprop ro.product.model
"FirmwareBrand": "", // adb.exe shell getprop ro.product.name
"FirmwareTags": "", // adb.exe shell getprop ro.build.tags
"FirmwareType": "", // adb.exe shell getprop ro.build.type
"FirmwareFingerprint": "" // adb.exe shell getprop ro.build.fingerprint

(Copied from NecroBot readme)
```

I dont know if there is any app which gives you these values..

I think is important to use device_info data, because official app always sends this data, if you dont send it you are not using the official app.

Also it's important to use altitude values, i thing most of bots use altitude = 0.

**Pull request merged**
