### PR TITLE
Do you support es6?

### PR DESCRIPTION
**Pull request by jimmywarting**
Want to know where you stand on es6 syntax before i make more PR

### CODE REVIEW

**Comment by Nickforall** [comment]
Suggestion, make variables like below constants.

``` javascript
var api_url = 'https://pgorelease.nianticlabs.com/plfe/rpc';
var events = require('events');
```

**Comment by Armax** [comment]
No atm we prefer to use pure node.js

**Comment by Nickforall** [comment]
ES6 is pretty much pure Node.js. Their whole documentation is written in ES6.

**Comment by jimmywarting** [comment]
> No atm we prefer to use pure node.js

Then you won't see any more PR from me 😞 

> ES6 is pretty much pure Node.js. Their whole documentation is written in ES6.

Exactly! This will not be used in the browser, only node. And node support it!

**Pull request merged**
