### PR TITLE
add player update and make all enum return enum value than integer and use item capture

### PR DESCRIPTION
**Pull request by billyriantono**
add player update and make all enum return enum value than integer
fixing for CatchPokemonResponse

### CODE REVIEW

**Comment by zckrs** [comment]
What are differences between PlayerUpdate and SetLocation?

**Comment by billyriantono** [comment]
Player Update send the loc to PoGO API server

**Comment by zckrs** [comment]
Thank you for precision.

**Comment by billyriantono** [comment]
adding for use item capture also

**Comment by zckrs** [comment]
Why closing this 🙁?

**Comment by billyriantono** [comment]
there is conflict need to be fixed first

**Pull request closed without merging**
