### PR TITLE
adding forts example and commenting problematic fields on proto file

### PR DESCRIPTION
**Pull request by segura2010**
Commented CaptureAward on CatchPokemonResponse because catch pokemons doesnt work with it

commented egg_km_walked_target on PokemonData because sometimes it give error

added pokestops (forts) usage in example.js

### CODE REVIEW

**Comment by sameerkanda** [comment]
@segura2010 Thanks for the code! I'm getting a lot of fortresponse.result == 4, any idea what it means? Also wondering if other results are possible?

**Comment by sameerkanda** [comment]
Oh nvm, its inventory full

**Comment by necm1** [comment]
I'm sorry for this question, but what's 'WildPokemon'?
I'm getting a error at this line https://github.com/Armax/Pokemon-GO-node-api/pull/87/commits/ae914ca315966d75cb64a53c6356fd274420c944#diff-65d7f35d2dc8f88273f9b1e3438d3af2R105

> TypeError: Cannot read property 'WildPokemon' of undefined

**Comment by BlackRosie** [comment]
Im getting null for the encountered id causing transfer to fail because no id. 

any ideas why  pokemon: { **Id: null,** PokemonId: 50, cp: null }

`2016-07-28T17:59:07-0400 <log> Trainer.js:264 (Trainer.method.catchNearbyPokemon) [+] currentPokemon
2016-07-28T17:59:07-0400 <log> Trainer.js:265 (Trainer.method.catchNearbyPokemon) { EncounterId: Long { low: 34657933, high: 1921311376, unsigned: true },
  LastModifiedMs: Long { low: 864332231, high: 342, unsigned: false },
  Latitude: 26.642152300767574,
  Longitude: -81.87045379756668,
  SpawnPointId: '88db41e3eb3',
  pokemon: { Id: null, PokemonId: 50, cp: null },`

**Pull request closed without merging**
