### PR TITLE
Updated it to be a es6 class

### PR DESCRIPTION
**Pull request by jimmywarting**

### CODE REVIEW

**Comment by Armax** [comment]
no.

**Comment by laterbreh** [comment]
Why are you wasting your time re-writing code that's already OOP?

**Comment by jimmywarting** [comment]
@Armax would you care to explain why you wouldn't want it?
And don't say it's cuz of your own taste. Want a reason.

**Comment by maxnowack** [comment]
@Armax sorry, but I don't understand you. You're allowing es6 destructors which are breaking the support for node < v6 but blocking es6 classes for no reason? I don't get it ...
@laterbreh rewritten code which is more clearer than the old one, is never a waste of time

**Comment by stoffern** [comment]
I have rewritten all of the code to ES6. and i have written it from https://github.com/stoffern/pgoapi
The original API and not a copy API that this is based on...

**Comment by laterbreh** [comment]
@stoffern He credits and sources the same link at the bottom of this readme.

**Pull request closed without merging**
