### PR TITLE
Show WildPokemon cp

### PR DESCRIPTION
**Pull request by sameerkanda**
Not sure how this works, but looks like WildPokemon information is missing, I'm guessing there's more information that can be added as well?

### CODE REVIEW

**Comment by reecube** [comment]
And this works? Because the WildPokemon have different cp for all player.

**Comment by sameerkanda** [comment]
I tested it on my side and it works

**Comment by filharvey** [comment]
Looks good to me as well. Please merge

**Comment by andnp** [comment]
This is great! I've been needing this functionality, and hadn't gotten around to it yet. Good work!

**Comment by TomVivant** [comment]
What about MapPokemon ?

**Pull request merged**
